### PR TITLE
Adding setup.py

### PR DESCRIPTION
**Pull request by 12944qwerty**
Setup.py will just install requests and scratchapi2. If you need to change anything, do so. (this is my first pull and my first setup.py, so....)

### CODE REVIEW

**Comment by BonfireScratch** [comment]
@12944qwerty thank you! I was trying to find out a way to do that!

**Comment by BonfireScratch** [comment]
@12944qwerty how does it work?

**Comment by BonfireScratch** [comment]
@12944qwerty this actually breaks the point of the installer

**Comment by BonfireScratch** [comment]
@Snipet what do you think?

**Comment by 12944qwerty** [comment]
one of the setup options is `install_requires=`. That's how it works. The only thing is that you have to do, is run setup.py as well. But only once (right when you clone/pull)

**Comment by 12944qwerty** [comment]
@BonfireScratch What do you mean it brakes the point of the installer?

**Comment by Kenny2github** [comment]
@BonfireScratch You need to run setup.py *before* running launcher.py
@12944qwerty You should have updated the documentation to mention running setup.py before launcher.py

**Comment by BonfireScratch** [comment]
@12944qwerty @Kenny2github  if there is setup.py, then the launcher isn't used.

**Comment by 12944qwerty** [comment]
@Kenny2github i completely forgot about having to run setup.py before launcher.py

@BonfireScratch what do you mean?

**Comment by BonfireScratch** [comment]
@12944qwerty with setup.py, launcher doesn't have a purpose any more.

**Comment by 12944qwerty** [comment]
oh...

**Comment by BonfireScratch** [comment]
@12944qwerty so, versions don't get updated

**Comment by 12944qwerty** [comment]
so??? what's happening?

**Comment by BonfireScratch** [comment]
@12944qwerty if people's versions don't get updated, they miss out important features

**Comment by 12944qwerty** [comment]
but how would they not get updated? just update setup.py...

**Pull request merged**
